CLIMATE:
  SEA: 0
  CONTINENTAL: 1
  OCEANIC: 2
  MEDITERRANEAN: 3
  TROPICAL: 4
  ARID: 5
  DESERT: 6
  NORDIC: 7
  POLAR: 8
  UNKNOWN: 9
RELIEF:
  UNKNOWN: 0
  FLAT: 1
  PLAIN: 2
  ROCKY: 3
  HILLS: 4
  MOUNTAINS: 5
VEGETATION:
  NONE: 0
  FOREST: 1
WATER:
  NONE: 0
  RIVER_SMALL: 1
  RIVER_MED: 2
  RIVER_LARGE: 3
  LAKE: 4
  SWAMP: 5
